// Code generated by mockery v2.49.1. DO NOT EDIT.

package fetch_test

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// MockprometheusMiddleware is an autogenerated mock type for the prometheusMiddleware type
type MockprometheusMiddleware struct {
	mock.Mock
}

// PrometheusMiddleware provides a mock function with given fields: handlerName, next
func (_m *MockprometheusMiddleware) PrometheusMiddleware(handlerName string, next http.HandlerFunc) http.Handler {
	ret := _m.Called(handlerName, next)

	if len(ret) == 0 {
		panic("no return value specified for PrometheusMiddleware")
	}

	var r0 http.Handler
	if rf, ok := ret.Get(0).(func(string, http.HandlerFunc) http.Handler); ok {
		r0 = rf(handlerName, next)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(http.Handler)
		}
	}

	return r0
}

// NewMockprometheusMiddleware creates a new instance of MockprometheusMiddleware. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockprometheusMiddleware(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockprometheusMiddleware {
	mock := &MockprometheusMiddleware{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
