openapi: 3.0.3
info:
  title: Tender API
  description: Tender API Backend Service
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'
paths:
  /api/ping:
    get:
      summary: Simple ping
      operationId: ping
      responses:
        '200':
          description: A successful response
          content:
            application/json: { }
  /api/bids/new:
    post:
      summary: Create bid
      operationId: bidsCreate
      tags:
        - BIDS
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BidCreateRequest"
      responses:
        '200':
          description: Bid created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Bid"
        '400':
          description: Bid created error
          content:
            application/json: { }
        '405':
          description: Method not allowed
          content:
            application/json: { }
        '403':
          description: Status Forbidden
          content:
            application/json: { }
        '500':
          description: Status Internal Server Error
          content:
            application/json: { }
  /api/bids/{bidID}/feedback:
    put:
      summary: Create feedback bid
      operationId: feedbackBids
      tags:
        - BIDS
      parameters:
        - in: path
          name: bidID
          schema:
            type: string
          required: true
          description: id предложения
        - in: query
          name: username
          required: true
          schema:
            type: string
          description: Имя ответственного за организацию тендера к этому комментируемому предложению
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/FeedbackCreateRequest"
      responses:
        '200':
          description: Bid created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Feedback"
        '400':
          description: feedback created error
          content:
            application/json: { }
        '405':
          description: Method not allowed
          content:
            application/json: { }
        '403':
          description: Status Forbidden
          content:
            application/json: { }
        '500':
          description: Status Internal Server Error
          content:
            application/json: { }
  /api/bids/{tenderID}/list:
    get:
      summary: Fetch list bids by tender
      operationId: fetchListByTender
      tags:
        - BIDS
      parameters:
        - in: path
          name: tenderID
          schema:
            type: string
          required: true
          description: id тендера
        - in: query
          name: username
          required: true
          schema:
            type: string
          description: Имя ответственного за организацию тендера
      responses:
        '200':
          description: Bids fetch successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Bid"
        '400':
          description: bids fetch error
          content:
            application/json: { }
        '405':
          description: Method not allowed
          content:
            application/json: { }
        '403':
          description: Status Forbidden
          content:
            application/json: { }
        '500':
          description: Status Internal Server Error
          content:
            application/json: { }
  /api/bids/my:
    get:
      summary: Fetch list bids by user
      operationId: fetchListByUser
      tags:
        - BIDS
      parameters:
        - in: query
          name: username
          required: true
          schema:
            type: string
          description: Имя ответственного за предложения
      responses:
        '200':
          description: Bids fetch successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Bid"
        '400':
          description: bids fetch error
          content:
            application/json: { }
        '405':
          description: Method not allowed
          content:
            application/json: { }
        '403':
          description: Status Forbidden
          content:
            application/json: { }
        '500':
          description: Status Internal Server Error
          content:
            application/json: { }
  /api/bids/{tenderID}/reviews:
    get:
      summary: Fetch reviews for bid
      operationId: FetchReviews
      tags:
        - BIDS
      parameters:
        - in: path
          name: tenderID
          schema:
            type: string
          required: true
          description: id тендера
        - in: query
          name: username
          required: true
          schema:
            type: string
          description: Имя ответственного за организацию этого тендера
        - in: query
          name: organizationId
          required: true
          schema:
            type: string
          description: id ответственной организации этого тендера
        - in: query
          name: authorUsername
          required: true
          schema:
            type: string
          description: Автор, отзывы на предложения которого  нужно вывести
      responses:
        '200':
          description: Bids fetch feedback successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Feedback"
        '400':
          description: Bids fetch feedback error
          content:
            application/json: { }
        '405':
          description: Method not allowed
          content:
            application/json: { }
        '403':
          description: Status Forbidden
          content:
            application/json: { }
        '500':
          description: Status Internal Server Error
          content:
            application/json: { }
  /api/bids/{bidID}/edit:
    patch:
      summary: Edit bid
      operationId: EditBid
      tags:
        - BIDS
      parameters:
        - in: path
          name: bidID
          schema:
            type: string
          required: true
          description: id предложения
        - in: query
          name: username
          required: true
          schema:
            type: string
          description: Имя ответственного за предложение
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BidEditRequest"
      responses:
        '200':
          description: Bid edit successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Bid"
        '400':
          description: bid edit error
          content:
            application/json: { }
        '405':
          description: Method not allowed
          content:
            application/json: { }
        '403':
          description: Status Forbidden
          content:
            application/json: { }
        '500':
          description: Status Internal Server Error
          content:
            application/json: { }
  /api/bids/{bidID}/rollback/{version}:
    put:
      summary: Rollback bid
      operationId: RollbackBid
      tags:
        - BIDS
      parameters:
        - in: path
          name: bidID
          schema:
            type: string
          required: true
          description: id предложения
        - in: path
          name: version
          schema:
            type: string
          required: true
          description: версия для отката предложения
        - in: query
          name: username
          required: true
          schema:
            type: string
          description: Имя ответственного за предложение
      responses:
        '200':
          description: Bid rollback successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Bid"
        '400':
          description: bid rollback error
          content:
            application/json: { }
        '405':
          description: Method not allowed
          content:
            application/json: { }
        '403':
          description: Status Forbidden
          content:
            application/json: { }
        '500':
          description: Status Internal Server Error
          content:
            application/json: { }
  /api/bids/{bidID}/status:
    get:
      summary: Fetch bid status
      operationId: FetchBidStatus
      tags:
        - BIDS
      parameters:
        - in: path
          name: bidID
          schema:
            type: string
          required: true
          description: id предложения
        - in: query
          name: username
          required: true
          schema:
            type: string
          description: Имя ответственного за предложение
      responses:
        '200':
          description: Bids fetch status successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Bid"
        '400':
          description: bids status fetch error
          content:
            application/json: { }
        '405':
          description: Method not allowed
          content:
            application/json: { }
        '403':
          description: Status Forbidden
          content:
            application/json: { }
        '500':
          description: Status Internal Server Error
          content:
            application/json: { }
    put:
      summary: Put new status bid
      operationId: PutStatusBid
      tags:
        - BIDS
      parameters:
        - in: path
          name: bidID
          schema:
            type: string
          required: true
          description: id предложения
        - in: query
          name: username
          required: true
          schema:
            type: string
          description: Имя ответственного за предложение
        - in: query
          name: status
          required: true
          schema:
            type: string
          description: Статус предложения
      responses:
        '200':
          description: Bid status edit successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Bid"
        '400':
          description: bid status edit error
          content:
            application/json: { }
        '405':
          description: Method not allowed
          content:
            application/json: { }
        '403':
          description: Status Forbidden
          content:
            application/json: { }
        '500':
          description: Status Internal Server Error
          content:
            application/json: { }
  /api/bids/{bidID}/submit_decision:
    put:
      summary: Bid submit decision
      operationId: SubmitDecisionBid
      tags:
        - BIDS
      parameters:
        - in: path
          name: bidID
          schema:
            type: string
          required: true
          description: id предложения
        - in: query
          name: organizationId
          schema:
            type: string
          required: true
          description: id организации ответственной за тендер
        - in: query
          name: username
          required: true
          schema:
            type: string
          description: Имя ответственного за организацию тендера
        - in: query
          name: decision
          required: true
          description: Решение по тендеру
          schema:
            type: string
            enum: ["APPROVED", "REJECTED"]
      responses:
        '200':
          description: Bid submit decision successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Bid"
        '400':
          description: bid submit decision error
          content:
            application/json: { }
        '405':
          description: Method not allowed
          content:
            application/json: { }
        '403':
          description: Status Forbidden
          content:
            application/json: { }
        '500':
          description: Status Internal Server Error
          content:
            application/json: { }
components:
  schemas:
    BidCreateRequest:
      title: "Запрос на создание предложения"
      type: object
      required:
        - name
        - description
        - tenderId
        - status
        - creatorUsername
        - organizationId
      properties:
        name:
          type: string
          format: text
          example: "Имя предложения"
        description:
          type: string
          format: text
          example: "Описание предложения"
        creatorUsername:
          type: string
          format: text
          example: "User1"
        tenderId:
          type: string
          format: string
          example: "550e8400-e29b-41d4-a716-446655440000"
        status:
          type: string
          format: text
          example: "CREATED"
    FeedbackCreateRequest:
      title: "Запрос на создание отзыва к предложению"
      type: object
      required:
        - description
      properties:
        description:
          type: string
          format: text
          example: "Отзыв"
    BidEditRequest:
      title: "Запрос на редактирование предложения"
      type: object
      required:
        - name
        - description
        - status
      properties:
        name:
          type: string
          format: text
          example: "Имя предложения"
        description:
          type: string
          format: text
          example: "Описание предложения"
        status:
          type: string
          format: text
          example: "PUBLISHED"
    Feedback:
      type: object
      title: Отзыв на предложение
      properties:
        id:
          type: string
          format: string
          example: "550e8400-e29b-41d4-a716-446655440000"
        bid_id:
          type: string
          format: text
          example: "550e8400-e29b-41d4-a716-446655440000"
        description:
          type: string
          format: text
          example: "Отзыв"
        responsible:
          type: string
          format: string
          example: "550e8400-e29b-41d4-a716-446655440000"
        created_at:
          type: string
          format: string
          example: "25.01.1994"
    Bid:
      type: object
      title: "Предложение"
      properties:
        id:
          type: string
          format: text
          example: "a6929720-17b0-45b4-bd54-76350fe5119b"
        name:
          type: string
          format: text
          example: "Имя предложения"
        description:
          type: string
          format: text
          example: "Описание предложения"
        status:
          type: string
          format: text
          example: "CREATED"
        tenderId:
          type: string
          format: string
          example: "550e8400-e29b-41d4-a716-446655440000"
        version:
          type: string
          format: text
          example: 1
        responsible:
          type: string
          format: string
          example: "550e8400-e29b-41d4-a716-446655440000"