// Code generated by mockery v2.49.1. DO NOT EDIT.

package tender_test

import (
	model "TenderServiceApi/internal/model"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockserviceOrganization is an autogenerated mock type for the serviceOrganization type
type MockserviceOrganization struct {
	mock.Mock
}

// CheckResponsible provides a mock function with given fields: ctx, username, organizationId
func (_m *MockserviceOrganization) CheckResponsible(ctx context.Context, username string, organizationId string) (model.OrganizationResponsible, error) {
	ret := _m.Called(ctx, username, organizationId)

	if len(ret) == 0 {
		panic("no return value specified for CheckResponsible")
	}

	var r0 model.OrganizationResponsible
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (model.OrganizationResponsible, error)); ok {
		return rf(ctx, username, organizationId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) model.OrganizationResponsible); ok {
		r0 = rf(ctx, username, organizationId)
	} else {
		r0 = ret.Get(0).(model.OrganizationResponsible)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, username, organizationId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchById provides a mock function with given fields: ctx, id
func (_m *MockserviceOrganization) FetchById(ctx context.Context, id string) (model.Organization, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FetchById")
	}

	var r0 model.Organization
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.Organization, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.Organization); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(model.Organization)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchRelationsById provides a mock function with given fields: ctx, id
func (_m *MockserviceOrganization) FetchRelationsById(ctx context.Context, id string) (model.OrganizationResponsible, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FetchRelationsById")
	}

	var r0 model.OrganizationResponsible
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.OrganizationResponsible, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.OrganizationResponsible); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(model.OrganizationResponsible)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockserviceOrganization creates a new instance of MockserviceOrganization. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockserviceOrganization(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockserviceOrganization {
	mock := &MockserviceOrganization{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
