// Code generated by mockery v2.49.1. DO NOT EDIT.

package edit_test

import (
	model "TenderServiceApi/internal/model"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Mockrepository is an autogenerated mock type for the repository type
type Mockrepository struct {
	mock.Mock
}

// Edit provides a mock function with given fields: ctx, bidNew, bid
func (_m *Mockrepository) Edit(ctx context.Context, bidNew model.Bids, bid model.Bids) (model.Bids, error) {
	ret := _m.Called(ctx, bidNew, bid)

	if len(ret) == 0 {
		panic("no return value specified for Edit")
	}

	var r0 model.Bids
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Bids, model.Bids) (model.Bids, error)); ok {
		return rf(ctx, bidNew, bid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.Bids, model.Bids) model.Bids); ok {
		r0 = rf(ctx, bidNew, bid)
	} else {
		r0 = ret.Get(0).(model.Bids)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.Bids, model.Bids) error); ok {
		r1 = rf(ctx, bidNew, bid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchById provides a mock function with given fields: ctx, bidID
func (_m *Mockrepository) FetchById(ctx context.Context, bidID string) (model.Bids, error) {
	ret := _m.Called(ctx, bidID)

	if len(ret) == 0 {
		panic("no return value specified for FetchById")
	}

	var r0 model.Bids
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.Bids, error)); ok {
		return rf(ctx, bidID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.Bids); ok {
		r0 = rf(ctx, bidID)
	} else {
		r0 = ret.Get(0).(model.Bids)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, bidID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Rollback provides a mock function with given fields: ctx, id, version
func (_m *Mockrepository) Rollback(ctx context.Context, id string, version string) (model.Bids, error) {
	ret := _m.Called(ctx, id, version)

	if len(ret) == 0 {
		panic("no return value specified for Rollback")
	}

	var r0 model.Bids
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (model.Bids, error)); ok {
		return rf(ctx, id, version)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) model.Bids); ok {
		r0 = rf(ctx, id, version)
	} else {
		r0 = ret.Get(0).(model.Bids)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, id, version)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateStatus provides a mock function with given fields: ctx, bidID, status
func (_m *Mockrepository) UpdateStatus(ctx context.Context, bidID string, status string) (model.Bids, error) {
	ret := _m.Called(ctx, bidID, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 model.Bids
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (model.Bids, error)); ok {
		return rf(ctx, bidID, status)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) model.Bids); ok {
		r0 = rf(ctx, bidID, status)
	} else {
		r0 = ret.Get(0).(model.Bids)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, bidID, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockrepository creates a new instance of Mockrepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockrepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Mockrepository {
	mock := &Mockrepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
