// Code generated by mockery v2.49.1. DO NOT EDIT.

package edit_test

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockuseCaseBidVerify is an autogenerated mock type for the useCaseBidVerify type
type MockuseCaseBidVerify struct {
	mock.Mock
}

// CheckResponsible provides a mock function with given fields: ctx, username, bidID
func (_m *MockuseCaseBidVerify) CheckResponsible(ctx context.Context, username string, bidID string) (bool, error) {
	ret := _m.Called(ctx, username, bidID)

	if len(ret) == 0 {
		panic("no return value specified for CheckResponsible")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return rf(ctx, username, bidID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = rf(ctx, username, bidID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, username, bidID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockuseCaseBidVerify creates a new instance of MockuseCaseBidVerify. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockuseCaseBidVerify(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockuseCaseBidVerify {
	mock := &MockuseCaseBidVerify{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
