// Code generated by mockery v2.49.1. DO NOT EDIT.

package decision_test

import (
	model "TenderServiceApi/internal/model"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockbidRepository is an autogenerated mock type for the bidRepository type
type MockbidRepository struct {
	mock.Mock
}

// FetchById provides a mock function with given fields: ctx, bidID
func (_m *MockbidRepository) FetchById(ctx context.Context, bidID string) (model.Bids, error) {
	ret := _m.Called(ctx, bidID)

	if len(ret) == 0 {
		panic("no return value specified for FetchById")
	}

	var r0 model.Bids
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.Bids, error)); ok {
		return rf(ctx, bidID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.Bids); ok {
		r0 = rf(ctx, bidID)
	} else {
		r0 = ret.Get(0).(model.Bids)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, bidID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateStatus provides a mock function with given fields: ctx, bidID, status
func (_m *MockbidRepository) UpdateStatus(ctx context.Context, bidID string, status string) (model.Bids, error) {
	ret := _m.Called(ctx, bidID, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 model.Bids
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (model.Bids, error)); ok {
		return rf(ctx, bidID, status)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) model.Bids); ok {
		r0 = rf(ctx, bidID, status)
	} else {
		r0 = ret.Get(0).(model.Bids)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, bidID, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockbidRepository creates a new instance of MockbidRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockbidRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockbidRepository {
	mock := &MockbidRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
