// Code generated by mockery v2.49.1. DO NOT EDIT.

package decision_test

import (
	model "TenderServiceApi/internal/model"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockdecisionRepository is an autogenerated mock type for the decisionRepository type
type MockdecisionRepository struct {
	mock.Mock
}

// FetchByBidID provides a mock function with given fields: ctx, bidID
func (_m *MockdecisionRepository) FetchByBidID(ctx context.Context, bidID string) ([]model.BidsDecisions, error) {
	ret := _m.Called(ctx, bidID)

	if len(ret) == 0 {
		panic("no return value specified for FetchByBidID")
	}

	var r0 []model.BidsDecisions
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]model.BidsDecisions, error)); ok {
		return rf(ctx, bidID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []model.BidsDecisions); ok {
		r0 = rf(ctx, bidID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.BidsDecisions)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, bidID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: ctx, bidID, decision, responsible
func (_m *MockdecisionRepository) Save(ctx context.Context, bidID string, decision string, responsible string) error {
	ret := _m.Called(ctx, bidID, decision, responsible)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, bidID, decision, responsible)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockdecisionRepository creates a new instance of MockdecisionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockdecisionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockdecisionRepository {
	mock := &MockdecisionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
