// Code generated by mockery v2.49.1. DO NOT EDIT.

package decision_test

import (
	model "TenderServiceApi/internal/model"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MocktenderRepository is an autogenerated mock type for the tenderRepository type
type MocktenderRepository struct {
	mock.Mock
}

// UpdateStatus provides a mock function with given fields: ctx, tenderId, status
func (_m *MocktenderRepository) UpdateStatus(ctx context.Context, tenderId string, status string) (model.Tender, error) {
	ret := _m.Called(ctx, tenderId, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 model.Tender
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (model.Tender, error)); ok {
		return rf(ctx, tenderId, status)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) model.Tender); ok {
		r0 = rf(ctx, tenderId, status)
	} else {
		r0 = ret.Get(0).(model.Tender)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, tenderId, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMocktenderRepository creates a new instance of MocktenderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMocktenderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MocktenderRepository {
	mock := &MocktenderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
