// Code generated by mockery v2.49.1. DO NOT EDIT.

package fetch_test

import (
	model "TenderServiceApi/internal/model"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockuseCaseBidsFetch is an autogenerated mock type for the useCaseBidsFetch type
type MockuseCaseBidsFetch struct {
	mock.Mock
}

// FetchListByTender provides a mock function with given fields: ctx, username, tenderId
func (_m *MockuseCaseBidsFetch) FetchListByTender(ctx context.Context, username string, tenderId string) ([]model.Bids, error) {
	ret := _m.Called(ctx, username, tenderId)

	if len(ret) == 0 {
		panic("no return value specified for FetchListByTender")
	}

	var r0 []model.Bids
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]model.Bids, error)); ok {
		return rf(ctx, username, tenderId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []model.Bids); ok {
		r0 = rf(ctx, username, tenderId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Bids)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, username, tenderId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchListByUser provides a mock function with given fields: ctx, username
func (_m *MockuseCaseBidsFetch) FetchListByUser(ctx context.Context, username string) ([]model.Bids, error) {
	ret := _m.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for FetchListByUser")
	}

	var r0 []model.Bids
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]model.Bids, error)); ok {
		return rf(ctx, username)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []model.Bids); ok {
		r0 = rf(ctx, username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Bids)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchStatus provides a mock function with given fields: ctx, username, bidsId
func (_m *MockuseCaseBidsFetch) FetchStatus(ctx context.Context, username string, bidsId string) (model.Bids, error) {
	ret := _m.Called(ctx, username, bidsId)

	if len(ret) == 0 {
		panic("no return value specified for FetchStatus")
	}

	var r0 model.Bids
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (model.Bids, error)); ok {
		return rf(ctx, username, bidsId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) model.Bids); ok {
		r0 = rf(ctx, username, bidsId)
	} else {
		r0 = ret.Get(0).(model.Bids)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, username, bidsId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockuseCaseBidsFetch creates a new instance of MockuseCaseBidsFetch. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockuseCaseBidsFetch(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockuseCaseBidsFetch {
	mock := &MockuseCaseBidsFetch{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
