// Code generated by mockery v2.49.1. DO NOT EDIT.

package create_test

import (
	model "TenderServiceApi/internal/model"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockrepositoryOrganization is an autogenerated mock type for the repositoryOrganization type
type MockrepositoryOrganization struct {
	mock.Mock
}

// FetchByUserName provides a mock function with given fields: ctx, username
func (_m *MockrepositoryOrganization) FetchByUserName(ctx context.Context, username string) (model.OrganizationResponsible, error) {
	ret := _m.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for FetchByUserName")
	}

	var r0 model.OrganizationResponsible
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.OrganizationResponsible, error)); ok {
		return rf(ctx, username)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.OrganizationResponsible); ok {
		r0 = rf(ctx, username)
	} else {
		r0 = ret.Get(0).(model.OrganizationResponsible)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockrepositoryOrganization creates a new instance of MockrepositoryOrganization. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockrepositoryOrganization(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockrepositoryOrganization {
	mock := &MockrepositoryOrganization{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
