// Code generated by mockery v2.49.1. DO NOT EDIT.

package create_test

import (
	model "TenderServiceApi/internal/model"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockrepositoryFeedback is an autogenerated mock type for the repositoryFeedback type
type MockrepositoryFeedback struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, saveModel
func (_m *MockrepositoryFeedback) Create(ctx context.Context, saveModel model.BidFeedback) (model.BidFeedback, error) {
	ret := _m.Called(ctx, saveModel)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 model.BidFeedback
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.BidFeedback) (model.BidFeedback, error)); ok {
		return rf(ctx, saveModel)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.BidFeedback) model.BidFeedback); ok {
		r0 = rf(ctx, saveModel)
	} else {
		r0 = ret.Get(0).(model.BidFeedback)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.BidFeedback) error); ok {
		r1 = rf(ctx, saveModel)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockrepositoryFeedback creates a new instance of MockrepositoryFeedback. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockrepositoryFeedback(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockrepositoryFeedback {
	mock := &MockrepositoryFeedback{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
