// Code generated by mockery v2.49.1. DO NOT EDIT.

package fetch_test

import mock "github.com/stretchr/testify/mock"

// Mocklog is an autogenerated mock type for the log type
type Mocklog struct {
	mock.Mock
}

// Error provides a mock function with given fields: msg, args
func (_m *Mocklog) Error(msg string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, msg)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// NewMocklog creates a new instance of Mocklog. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMocklog(t interface {
	mock.TestingT
	Cleanup(func())
}) *Mocklog {
	mock := &Mocklog{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
