-- +goose Up
-- +goose StatementBegin
CREATE TABLE tender_history
(
    id        INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    tender_id UUID REFERENCES tender (id) ON DELETE CASCADE,
    data      jsonb
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS tender_history
-- +goose StatementEnd
