// Code generated by mockery v2.49.1. DO NOT EDIT.

package mocks

import (
	model "TenderServiceApi/internal/model"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// service is an autogenerated mock type for the service type
type Service struct {
	mock.Mock
}

// FetchList provides a mock function with given fields: ctx, serviceType
func (_m *Service) FetchList(ctx context.Context, serviceType string) ([]model.Tender, error) {
	ret := _m.Called(ctx, serviceType)

	if len(ret) == 0 {
		panic("no return value specified for FetchList")
	}

	var r0 []model.Tender
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]model.Tender, error)); ok {
		return rf(ctx, serviceType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []model.Tender); ok {
		r0 = rf(ctx, serviceType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Tender)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, serviceType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// newService creates a new instance of service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
