// Code generated by mockery v2.49.1. DO NOT EDIT.

package fetch_test

import (
	model "TenderServiceApi/internal/model"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Mockrepository is an autogenerated mock type for the repository type
type Mockrepository struct {
	mock.Mock
}

// FetchReviews provides a mock function with given fields: ctx, tenderID, authorUsername, organizationID
func (_m *Mockrepository) FetchReviews(ctx context.Context, tenderID string, authorUsername string, organizationID string) ([]model.BidFeedback, error) {
	ret := _m.Called(ctx, tenderID, authorUsername, organizationID)

	if len(ret) == 0 {
		panic("no return value specified for FetchReviews")
	}

	var r0 []model.BidFeedback
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) ([]model.BidFeedback, error)); ok {
		return rf(ctx, tenderID, authorUsername, organizationID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) []model.BidFeedback); ok {
		r0 = rf(ctx, tenderID, authorUsername, organizationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.BidFeedback)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, tenderID, authorUsername, organizationID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockrepository creates a new instance of Mockrepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockrepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Mockrepository {
	mock := &Mockrepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
