// Code generated by mockery v2.49.1. DO NOT EDIT.

package fetch_test

import (
	model "TenderServiceApi/internal/model"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockuseCaseOrganizationVerify is an autogenerated mock type for the useCaseOrganizationVerify type
type MockuseCaseOrganizationVerify struct {
	mock.Mock
}

// CheckResponsible provides a mock function with given fields: ctx, username, organizationId
func (_m *MockuseCaseOrganizationVerify) CheckResponsible(ctx context.Context, username string, organizationId string) (model.OrganizationResponsible, error) {
	ret := _m.Called(ctx, username, organizationId)

	if len(ret) == 0 {
		panic("no return value specified for CheckResponsible")
	}

	var r0 model.OrganizationResponsible
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (model.OrganizationResponsible, error)); ok {
		return rf(ctx, username, organizationId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) model.OrganizationResponsible); ok {
		r0 = rf(ctx, username, organizationId)
	} else {
		r0 = ret.Get(0).(model.OrganizationResponsible)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, username, organizationId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockuseCaseOrganizationVerify creates a new instance of MockuseCaseOrganizationVerify. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockuseCaseOrganizationVerify(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockuseCaseOrganizationVerify {
	mock := &MockuseCaseOrganizationVerify{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
