// Code generated by mockery v2.49.1. DO NOT EDIT.

package edit_test

import (
	model "TenderServiceApi/internal/model"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Mockrepository is an autogenerated mock type for the repository type
type Mockrepository struct {
	mock.Mock
}

// Edit provides a mock function with given fields: ctx, tenderNew, tender
func (_m *Mockrepository) Edit(ctx context.Context, tenderNew model.Tender, tender model.Tender) (model.Tender, error) {
	ret := _m.Called(ctx, tenderNew, tender)

	if len(ret) == 0 {
		panic("no return value specified for Edit")
	}

	var r0 model.Tender
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Tender, model.Tender) (model.Tender, error)); ok {
		return rf(ctx, tenderNew, tender)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.Tender, model.Tender) model.Tender); ok {
		r0 = rf(ctx, tenderNew, tender)
	} else {
		r0 = ret.Get(0).(model.Tender)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.Tender, model.Tender) error); ok {
		r1 = rf(ctx, tenderNew, tender)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchById provides a mock function with given fields: ctx, tenderId
func (_m *Mockrepository) FetchById(ctx context.Context, tenderId string) (model.Tender, error) {
	ret := _m.Called(ctx, tenderId)

	if len(ret) == 0 {
		panic("no return value specified for FetchById")
	}

	var r0 model.Tender
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.Tender, error)); ok {
		return rf(ctx, tenderId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.Tender); ok {
		r0 = rf(ctx, tenderId)
	} else {
		r0 = ret.Get(0).(model.Tender)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tenderId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Rollback provides a mock function with given fields: ctx, id, version
func (_m *Mockrepository) Rollback(ctx context.Context, id string, version string) (model.Tender, error) {
	ret := _m.Called(ctx, id, version)

	if len(ret) == 0 {
		panic("no return value specified for Rollback")
	}

	var r0 model.Tender
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (model.Tender, error)); ok {
		return rf(ctx, id, version)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) model.Tender); ok {
		r0 = rf(ctx, id, version)
	} else {
		r0 = ret.Get(0).(model.Tender)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, id, version)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateStatus provides a mock function with given fields: ctx, tenderId, status
func (_m *Mockrepository) UpdateStatus(ctx context.Context, tenderId string, status string) (model.Tender, error) {
	ret := _m.Called(ctx, tenderId, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 model.Tender
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (model.Tender, error)); ok {
		return rf(ctx, tenderId, status)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) model.Tender); ok {
		r0 = rf(ctx, tenderId, status)
	} else {
		r0 = ret.Get(0).(model.Tender)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, tenderId, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockrepository creates a new instance of Mockrepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockrepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Mockrepository {
	mock := &Mockrepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
