version: '3.5'
volumes:
  db:

services:
  db:
    image: postgres:latest
    restart: always
    container_name: tender_service_api_db
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - DATABASE_HOST=$}
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - backend
networks:
  backend:
    driver: bridge

