// Code generated by mockery v2.49.1. DO NOT EDIT.

package create_test

import (
	model "TenderServiceApi/internal/model"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Mockrepository is an autogenerated mock type for the repository type
type Mockrepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, saveModel
func (_m *Mockrepository) Create(ctx context.Context, saveModel model.Bids) (model.Bids, error) {
	ret := _m.Called(ctx, saveModel)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 model.Bids
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Bids) (model.Bids, error)); ok {
		return rf(ctx, saveModel)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.Bids) model.Bids); ok {
		r0 = rf(ctx, saveModel)
	} else {
		r0 = ret.Get(0).(model.Bids)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.Bids) error); ok {
		r1 = rf(ctx, saveModel)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockrepository creates a new instance of Mockrepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockrepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Mockrepository {
	mock := &Mockrepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
