// Code generated by mockery v2.49.1. DO NOT EDIT.

package fetch_test

import (
	model "TenderServiceApi/internal/model"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Mockrepository is an autogenerated mock type for the repository type
type Mockrepository struct {
	mock.Mock
}

// FetchById provides a mock function with given fields: ctx, bidsId
func (_m *Mockrepository) FetchById(ctx context.Context, bidsId string) (model.Bids, error) {
	ret := _m.Called(ctx, bidsId)

	if len(ret) == 0 {
		panic("no return value specified for FetchById")
	}

	var r0 model.Bids
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.Bids, error)); ok {
		return rf(ctx, bidsId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.Bids); ok {
		r0 = rf(ctx, bidsId)
	} else {
		r0 = ret.Get(0).(model.Bids)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, bidsId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchListByTender provides a mock function with given fields: ctx, tenderId
func (_m *Mockrepository) FetchListByTender(ctx context.Context, tenderId string) ([]model.Bids, error) {
	ret := _m.Called(ctx, tenderId)

	if len(ret) == 0 {
		panic("no return value specified for FetchListByTender")
	}

	var r0 []model.Bids
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]model.Bids, error)); ok {
		return rf(ctx, tenderId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []model.Bids); ok {
		r0 = rf(ctx, tenderId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Bids)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tenderId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchListByUser provides a mock function with given fields: ctx, username
func (_m *Mockrepository) FetchListByUser(ctx context.Context, username string) ([]model.Bids, error) {
	ret := _m.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for FetchListByUser")
	}

	var r0 []model.Bids
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]model.Bids, error)); ok {
		return rf(ctx, username)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []model.Bids); ok {
		r0 = rf(ctx, username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Bids)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockrepository creates a new instance of Mockrepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockrepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Mockrepository {
	mock := &Mockrepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
